# Generated by Django 6.0.2 on 2026-03-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idempotentpayment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total',
        ),
    ]
